title: Foundation for Public Code
permalinks: pretty

remote_theme: publiccodenet/jekyll-theme
description: Enabling development of digital policy and software for public purposes. In order to deliver contemporary public digitial services that are inclusive, usable, adaptive, open and sustainable we need to work together. The Foundation for Public Code offers infrastructural services and products to enable Public Code development.

titles_from_headings:
  strip_title: true

show_breadcrumbs: true
toc: true